### ISSUE TITLE
cmd+opt+i overrides inspector shortcut 

### ISSUE THREAD

**Issue by woylie** [phenixdigital/phx_live_storybook#110]
If I press cmd+opt+i on a mac, the quick search panel is opened instead of the browser inspector (Firefox and Chrome).

The search panel is also opened when I only type `/` (opt + i in my keyboard layout). I don't know whether that's intended, but the shortcut rendered in the UI is cmd+k, and putting shortcuts on the option or alt key always leads to trouble, since the option and alt key are used to access characters and symbols. I can't type a `/` in the search input now, which isn't too bad, but I also cannot enter a `/` in any input I render in a component, which is kind of bad when it comes to testing input validation and sanitation.

**Comment by matthieuchabert** [comment]
Hi @woylie !

You're right about mapping `/` to the search panel. We'll remove this.

This fix should also remove the search bar opening on `cmd`+`opt`+`I`  if you mapped it to `/`.
