### ISSUE TITLE
User icon for a StoryEntry not correctly placed

### ISSUE THREAD

**Issue by benregn** [phenixdigital/phx_live_storybook#118]
The user icon for a `StoryEntry` isn't being placed correctly in relation to it's name.

<img width="162" alt="Screen Shot 2022-09-30 at 11 33 25 AM" src="https://user-images.githubusercontent.com/206066/193240985-5d25e539-b39e-4e11-9f78-a3cee39ede6d.png">

It looks like the [`story_class`](https://github.com/phenixdigital/phx_live_storybook/blob/3b091c712645c71ff67a0e4b062e0a7935f9eee7/lib/phx_live_storybook/live/sidebar.ex#L155) is missing these two classes: `lsb-flex` and `lsb-items-center`.

**Comment by cblavier** [comment]
Hey, this issue might be related to #111 which I will solve first.
Are you using Heroicons or FontAwesome?
