### ISSUE TITLE
configure live session names

### ISSUE THREAD

**Issue by woylie** [phenixdigital/phx_live_storybook#126]
I would like to be able to override the default live session names used by `live_storybook/2`. The background is that I'm serving two frontends (public/admin) with the same Phoenix application, which have two separate component style sheets. A different theme class is not sufficient to switch between the styles. Also, there are some components that are not shared between these frontends. For those reasons, I'd like to set up two separate storybooks in my application. But since the live session name is hardcoded at the moment, I get this error when I add the a second call to `live_storybook/2` to the router:

```elixir
** (RuntimeError) attempting to redefine live_session :live_storybook_iframe.
live_session routes must be declared in a single named block.
```

**Comment by cblavier** [comment]
`phx_live_storybook` is indeed meant to be mounted multiple time in a single app, even if I never tried it myself
I think we can add a new `:session_name` opt in the `live_storybook` macro of [router.ex](https://github.com/phenixdigital/phx_live_storybook/blob/main/lib/phx_live_storybook/router.ex).

Would you mind a PR?

**Comment by woylie** [comment]
Sure, I'll open a PR. We'll need `session_name` and `session_name_iframe` then. Or do you want to append the `_iframe` to the `session_name` option for the second live session?

**Comment by cblavier** [comment]
Thanks! I prefer the second choice (single `session_name` option)
