### ISSUE TITLE
pass additional params to live socket

### ISSUE THREAD

**Issue by woylie** [phenixdigital/phx_live_storybook#129]
It looks like currently it's not possible to pass additional parameters to the live socket: https://github.com/phenixdigital/phx_live_storybook/blob/1cc9c70ba28b42c60f06fdb3216c6a1f3da456e8/assets/js/iframe.js#L23

I'd like to be able to pass additional parameters similarly to how it works with hooks and uploaders.

In the style guide I built before live storybook was available, I used the live socket parameters to pass the design tokens to my live view, so that I can render overviews of available colors, font sizes etc. dynamically without editing any Elixir code when something changes.

```js
import scssVariables from "../css/admin/_export.scss";

let liveSocket = new LiveSocket("/live", Socket, {
  params: { _csrf_token: csrfToken, scssVariables: scssVariables },
  hooks: Hooks,
});
```

**Comment by cblavier** [comment]
That's clever. Then you parse scss from your Elixir code?

**Comment by woylie** [comment]
Not quite, `scssVariables` is already an object, so what I get in live view is something like this:

```elixir
%{
  "color-text-default" => "#020802",
  # ...
}
```

Unfortunately, this only works in the combination of webpack, scss, and css loader. You can read more about it here: https://www.mathiaspolligkeit.com/dev/design-systems-pt-6-variable-export/

**Comment by cblavier** [comment]
Ok thanks
I think this is a good feature to have: merge any additional params from `window.storybook.liveSocketParams` to the livesocket params object.
