### ISSUE TITLE
route helpers are hardcoded

### ISSUE THREAD

**Issue by woylie** [phenixdigital/phx_live_storybook#131]
We can mount multiple storybooks now and pass the `as` option to name the route helper, but in the rest of the library, the route helper name is hard coded, which means all the links in the sidebar will be wrong as soon as you set the `as` option.

I think we can add the route helper name to the session options of the live session, assign the value to the socket in a mount function, and use the route helper name from the assigns everywhere. What do you think?

**Comment by cblavier** [comment]
Sounds good to me 👌 want to do both PR at once? (with  #129)
We might need to revisit it again after phoenix 1.7 Is released as routes helpers are not enabled by default on a new phoenix app.

**Comment by woylie** [comment]
I'll open a separate PR for that.

**Comment by woylie** [comment]
> We might need to revisit it again after phoenix 1.7 Is released as routes helpers are not enabled by default on a new phoenix app.

I don't think we can do anything with verified routes in this context. So if we want this to work without route helpers, we can just pass the `path` passed to the macro along the same way as described, with the caveat that you wouldn't be able to call the macro within another `scope`. Alternatively, we could add another option for the full path as a string, but that seems a bit redundant.

There is nothing we'd need from Phoenix 1.7 to make this work, so we can build base the paths based on the `path` string right away and remove the route helper calls.

**Comment by cblavier** [comment]
Yes, disabling route helpers seems to be a good move.
I don't remember exactly where we are using them in the app. Is it widespread or not?
I you don't have time to look, I can investigate in a few days
