### ISSUE TITLE
guard_fail The guard clause can never succeed

### ISSUE THREAD

**Issue by woylie** [phenixdigital/phx_live_storybook#132]
When I `use PhxLiveStorybook` in my project, dialyzer returns a `guard_fail The guard clause can never succeed` warning. It just points to the line where `use` is used, so I don't know what the underlying issue is.

When I run dialyzer in `phx_live_storybook`, it returns a whole bunch of warnings. I'd suggest adding dialyxir to the project.

**Comment by cblavier** [comment]
I'm afraid to run dialixyr for the first time, but here we go! 🥷

**Comment by cblavier** [comment]
Not convinced at all, I checked all reported errors and they were all false positives

**Comment by woylie** [comment]
That's not true.

```
lib/phx_live_storybook/stories/story.ex:102:unknown_type
Unknown type: PhxLiveStorybook.Stories.Attr.t/0.
________________________________________________________________________________
lib/phx_live_storybook/stories/story.ex:103:unknown_type
Unknown type: PhxLiveStorybook.Stories.Slot.t/0.
________________________________________________________________________________
lib/phx_live_storybook/stories/story.ex:104:unknown_type
Unknown type: PhxLiveStorybook.Stories.Variation.t/0.
________________________________________________________________________________
lib/phx_live_storybook/stories/story.ex:104:unknown_type
Unknown type: PhxLiveStorybook.Stories.VariationGroup.t/0.
________________________________________________________________________________
lib/phx_live_storybook/stories/story.ex:115:unknown_type
Unknown type: PhxLiveStorybook.Stories.Attr.t/0.
________________________________________________________________________________
lib/phx_live_storybook/stories/story.ex:116:unknown_type
Unknown type: PhxLiveStorybook.Stories.Slot.t/0.
________________________________________________________________________________
lib/phx_live_storybook/stories/story.ex:117:unknown_type
Unknown type: PhxLiveStorybook.Stories.Variation.t/0.
________________________________________________________________________________
lib/phx_live_storybook/stories/story.ex:117:unknown_type
Unknown type: PhxLiveStorybook.Stories.VariationGroup.t/0.
```

None of these types are defined.

```
lib/mix/tasks/phx.gen.storybook.ex:42:call
The function call will not succeed.

Phoenix.Naming.underscore(_web_module :: atom())

breaks the contract
(String.t()) :: String.t()
```

`web_module` _is_ an atom, and `underscore/1` _does_ expect a string. Explicitly converting to a string resolves this and the other warnings for this module.

The warnings about non-existent Jason and Earmark functions are emitted because the dependencies are configured as `runtime: false` or `optional: true`. 

```
lib/phx_live_storybook/stories/story_validator.ex:205:no_return
Function bad_type!/3 has no local return.
```

This means that the function always raises. Not a false positive, but expected behaviour, so this can be ignored.

#142  fixes all of these issues, except for the missing type definitions. Note that this doesn't solve the original issue, though, which is that if you `use PhxLiveStorybook` in a project, you get the `"The guard clause can never succeed"` warning _in your project_.
