### ISSUE TITLE
block elements don't take up full width

### ISSUE THREAD

**Issue by woylie** [phenixdigital/phx_live_storybook#135]
Normally, elements with `display: block;` should take up the full width, but in the sandboxes of the stories and playground views, they don't. In the case of the playground, the sandbox is set to `display: flex;`, and changing this to `display: block;` resolves the issue. In the case of the stories view, there is no display property on the sandbox, but adding `display: block;` there solves the issue as well.

However, the flex box is used to center the items, so switching to block will align inline elements and less-than-full-width blocks left. I don't know what a good solution would be, but I'd very much prefer to preview my full-width components in full-width indeed, without needlessly adding `width: 100%` everywhere.

**Comment by cblavier** [comment]
Component `stories` export by default a `def container, do: :div` that you can override to render your components within an iframe.
We could improve this feature to pass it a tuple value: `{:div, "block"}`

WDYT?

**Comment by woylie** [comment]
That should work!

**Comment by cblavier** [comment]
I will do something similar to the live_view api: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#__using__/1

**Comment by cblavier** [comment]
Until I add this feature, you can use a template on your story to wrap your component:

```
  def template do
    """
    <div class="w-full" lsb-code-hidden>
      <.lsb-variation/>
    </div>
    """
  end
```
