### ISSUE TITLE
missing variation_id in assign

### ISSUE THREAD

**Issue by pollingj** [phenixdigital/phx_live_storybook#146]
Version: 0.4.5

I'm just trying to write an animation to a show and hide for a banner.  As part of that I also want to update an assigned value `hidden`.

```
  def show_banner(js \\ %JS{}, id) do
    js
    |> JS.show(
      transition: {
        "transition ease-in-out duration-200",
        "opacity-0 translate-y-4",
        "opacity-100 translate-y-0"
      },
      to: "##{id}"
    )
    |> JS.push("assign", value: %{hidden: false})
  end
```

The problem here is that Storybook then gives me the warning `missing variation_id in assign`.  

If I do the `JS.push("assign.....` directly in the variation template this works, because the Storybook code automatically adds in the variation_id.  Am I missing something obvious?  I'm not really wanting to have to force in the variation_id to `show_banner` as that will create a dependency on Storybook within the component.  Apologies if I'm missing something obvious here.

**Comment by cblavier** [comment]
You indeed need to pass variation_id in the pushed value.

Here is an example: https://github.com/phenixdigital/phx_live_storybook_sample/blob/main/storybook/components/templates/slideover.story.exs

It seems that by relying on the `"assign"` phx event, you already created a dependency on Storybook, didn't you?

**Comment by pollingj** [comment]
Thanks for the quick reply.  With the `"assign"` I was looking for a way just to manage the state in the component, so that I could add in additional control in the component HTML.  That's just a standard LiveView JS thing isn't it, rather than a specific Storybook part isn't it?

The example looks useful though thanks, I think I can take that and pipe it from the Storybook variation into the components `show_banner` function.

**Comment by cblavier** [comment]
`JS.push` is standard
the `"assign"` event is not, it is implemented here in phx_live_storybook :)  https://github.com/phenixdigital/phx_live_storybook/blob/main/lib/phx_live_storybook/live/story_live.ex#L484

**Comment by pollingj** [comment]
Ah, I'd missed that, thanks.  Looks like I need to rethink my strategy a bit here, as I definitely don't want the components to have any reliance on Storybook.
