### ISSUE TITLE
Opening the Source Code in Visual Studio Code while in Dev Mode

### ISSUE THREAD

**Issue by abhijit-kar** [phenixdigital/phx_live_storybook#147]
Hi Team,

I came across this awesome project, and I was thinking if a small feature can be added to improve dev experience. I don't know where this thing belongs, so I want your input.

I created a live component, which can be put at the top of any other component:
```elixir
<%= if env(:dev) do %>
   <.live_component
      module={DerpyCoderWeb.InspectorComponent}
      file={__ENV__.file}
      id={"#{__MODULE__}-inspector"}
   />
<% end %>
```

DerpyCoderWeb.InspectorComponent:

![Open In VS Code](https://user-images.githubusercontent.com/25662120/195562528-450306fb-c154-4931-b984-7e29a8987bc9.png)

![Show in Catalog](https://user-images.githubusercontent.com/25662120/195562758-6289e1c0-9dc6-4dbc-b89d-ff046ce5e4a6.png)

```html
<div class="absolute -top-12 flex justify-center w-full">
  <button class="rounded-tl-lg rounded-bl-lg p-2 bg-slate-100 m-0">
    <HeroIcons.Solid.eye class="h-6 w-6 text-gray-500" title="Show in Catalog" />
  </button>
  <button
    phx-click="inspect-source"
    phx-value-file={@file}
    class="rounded-tr-lg rounded-br-lg p-2 bg-slate-100 m-0 border-l border-slate-200"
    phx-target={@myself}
  >
    <HeroIcons.Solid.code class="h-6 w-6 text-gray-500" title="Open in VS Code" />
  </button>
</div>
```

```elixir
defmodule DerpyCoderWeb.InspectorComponent do
  @moduledoc """
  Useful component for development.
  Can be embedded into other components, which will allow developers to open
  the source code of the component directly from browser.
  """
  use DerpyCoderWeb, :live_component

  def handle_event("inspect-source", %{"file" => file}, socket) do
    inspect_source(file)

    {:noreply, socket}
  end

  defp inspect_source(path, line \\ 1) do
    System.cmd("code", ["--goto", "#{path}:#{line}"])
  end
end
```

On click of Open in VS Code Icon, the VS Code Editor opens up. This helps tremendously, because now I don't have to guess the name of the file or where the code is, for a random component I'm looking at in a web page!!

https://user-images.githubusercontent.com/25662120/195563246-1d8c087a-97ec-4d05-926e-a41b09d9d87f.mov

P.S. I have recently started learning about Phoenix & Live View and new version changed a lot of the things. I am waiting for latest Phoenix Release to start relearning again. 😅

**Comment by abhijit-kar** [comment]
I almost forgot:

`export ELIXIR_EDITOR="code --goto __FILE__:__LINE__"` needs to be part of `~/.zshenv` or wherever global env variables can be stored, for this to work.

**Comment by abhijit-kar** [comment]
The eye icon, with `Show in Catalog` text, can link to the Phoenix Storybook component page.

P.S. This small thing was inspired by: [bit.dev](https://bit.dev)


https://user-images.githubusercontent.com/25662120/195569175-9c793d15-cb99-41a3-a96e-49ed9b3cf6df.mov

**Comment by cblavier** [comment]
Thanks for the idea Abhijit, I will think on how it can be integrated into storybook (while still being agnostic to the code editor: it should also work with vim or TextMate)

**Comment by abhijit-kar** [comment]
@cblavier,

Thank you for considering this.
