### ISSUE TITLE
Integrating into phoenix project without tailwind (or other css framework) renders with browser default font

### ISSUE THREAD

**Issue by LostKobrakai** [phenixdigital/phx_live_storybook#151]
I've just included storybook into a fresh 1.6 phoenix install (no tailwind) and the storybook seems to render Times New Roman for plain body text. Storybook should probably bring its own css (incl. whichever resets it needs).

**Comment by cblavier** [comment]
Projects not using Tailwind now get a CSS file styling their sandbox with

```css
font-family: ui-sans-serif, system-ui;
```
