### ISSUE TITLE
Using icon font in components

### ISSUE THREAD

**Issue by lessless** [phenixdigital/phx_live_storybook#171]
Hi,

We are using custom icon fonts for our buttons through an extended Tailwind scheme and also have a few more tweaks in our tailwind config, which makes it looks like this 

```
module.exports = {
  theme: {
    extend: {
      content: {
        'upload-cloud': '"\uE9b4"',
      },
      colors: {
        'mv-primary': '#01031b',
      },
      backgroundImage: {
        'bg-forms': "url('/images/signup/background_1080p.jpg')",
      },
      fontFamily: {
        'open-sans': ['Open Sans'],
      },
    },
    container: {
      center: true,
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
```

Are there any ways to make this work in PhxLive Storybook currently?

**Comment by cblavier** [comment]
Hey Yevhenii 👋
With storybook you still bring your own `tailwind.config.js` file with along your CSS files, so I don't think it should be an issue. Is-it?

**Comment by lessless** [comment]
Yeah, this should work. 

Would you please point me to the documentation or sample of how to set it up? 

I tried to look into the docs and sample repo but couldn't find it. 

I'm probably missing something.

**Comment by cblavier** [comment]
I will try one of your tweak right now in my sample app, and let you know!

**Comment by cblavier** [comment]
In this file there is already a working example of custom tailwind colors: 

https://github.com/phenixdigital/phx_live_storybook_sample/blob/main/assets/tailwind.config.js

**Comment by lessless** [comment]
Ah, so the storybook reuses tailwind.config.js from the host project?

**Comment by cblavier** [comment]
I'm not really sure what you mean:
- phx_live_storybook has its own `tailwind.config.js` to declare its own styles, which you cannot override
- your host project can also use tailwind (or whichever CSS framework of your choice). The `tailwind.config.js` which I linked earlier is a config file from a sample host app, which declares colors used by the sample app components.

Does it sound more clear?

**Comment by lessless** [comment]
Totally! 

I thought that `phx_live_storybook` is using a separate Tailwind config but that was because I didn't `@import`  icon font in it :) 

Thank you for the awesome project and your help 🙏
