### ISSUE TITLE
Documentation "Sandboxing components" contains a couple of confusing directions

### ISSUE THREAD

**Issue by ArthurClemens** [phenixdigital/phx_live_storybook#179]
[Section 1](https://hexdocs.pm/phx_live_storybook/sandboxing.html#1-what-js-context-do-your-components-share-with-the-storybook) contains:
> "create a JS file"

The code example says
> `// assets/js/my_components.js`

And continues
> Then set the `js_path: "/assets/js/components.js"` option to the storybook within your `config.exs` file.

To me this is confusing:
- The generator already created file `assets/js/storybook.js` with this contents - this could be mentioned
- Inconsisitency of `my_components.js` and `components.js`
- `config.ex` does not contain an entry for `js_path` (to my knowledge) - shouldn't this be `storybook.ex`? If true, should the file created at "create a JS file" not be `storybook.js`?

[Section 3](https://hexdocs.pm/phx_live_storybook/sandboxing.html#3-how-should-you-provide-the-style-of-your-components) contains:
> Just (like for JS), set the `css_path: "/assets/css/components.css"` option in config.exs.

To me this is confusing:
- Reading how to solve a CSS import should not require to first read JS instructions - this piece of info should be possible to understand standalone
- Same as above: should this setting be written in `storybook.ex`?
- Because the generator has created `storybook.css`, do I need to create a separate file `component.css`, or should I just expand `storybook.css`? I can figure it out, the the extra time required could be spent better.

**Comment by cblavier** [comment]
Thank your Arthur, this is indeed misleading.
I will improve it later today. Would you like to review my PR?
