### ISSUE TITLE
Add support for multiple components in one story

### ISSUE THREAD

**Issue by ArthurClemens** [phenixdigital/phx_live_storybook#181]
If I have a component library with components Button and Icon, and I would like to show an icon inside a button, the markup would normally be something like this:

```
<.button>
  <.icon name="todo" />
  Add To Do
</.button>
```

But only the component that is assigned to `function` is accessible:

```
def function, do: &MyLib.Component.button/1
```

So in order to work, the above markup inside a story becomes:

```
<.button>
  <MyLib.Component.icon name="todo" />
  Add To Do
</.button>
```

Which is not what a user should need to write.

**Comment by matthieuchabert** [comment]
Hi @ArthurClemens !

You might want to check out the documentation about [aliases and imports](https://github.com/phenixdigital/phx_live_storybook/blob/main/guides/components.md#aliases--imports). I think this will solve your problem.

**Comment by ArthurClemens** [comment]
Yes, `imports` works for me.
