### ISSUE TITLE
Stories tab: a high code fragment creates a large gap above the rendered component

### ISSUE THREAD

**Issue by ArthurClemens** [phenixdigital/phx_live_storybook#183]
This becomes apparent when using a template inside a `VariationGroup`, which creates quite some markup.

Current rendering:

![image](https://user-images.githubusercontent.com/350303/201768572-756c10b9-d659-450b-8d00-ff0a6d14d93f.png)

Suggestion: when using `align-items: flex-start`, the rendered component is immediately in view:

![image](https://user-images.githubusercontent.com/350303/201768741-54059d59-3d6f-4be7-ba79-e5aa870b1aef.png)

**Comment by cblavier** [comment]
That is the same issue than #178

You can deal with different container layouts with existing options. There is still room for improvement but I will deal with it in #178

**Comment by ArthurClemens** [comment]
I am already using `def container, do: {:div, class: "block"}`. Apparently I need to use another modifier class to correct the vertical layout.

**Comment by cblavier** [comment]
You should use other classes, but I think you will have to use storybook prefixed classes (I will improve documentation in that respect)

```
def container, do: {:div, class: "lsb-flex lsb-flex-col lsb-h-full lsb-items-center lsb-space-y-2"}
```
