### ISSUE TITLE
Alternate CSS frameworks?

### ISSUE THREAD

**Issue by andyl** [phenixdigital/phx_live_storybook#194]
Does `phx_live_storybook` work with alternate CSS frameworks like `Bootstrap`, `Milligram` or `Bulma`?

**Comment by cblavier** [comment]
Yes it does!
The storybook itself will always be rendered with Tailwind, but your components can use the CSS framework of your choice.
When you generate your storybook make sure to pass the proper flag:

```sh
$> mix phx.gen.storybook --no-tailwind
```

**Comment by andyl** [comment]
Thank you!
