### ISSUE TITLE
Story files as .exs

### ISSUE THREAD

**Issue by LostKobrakai** [phenixdigital/phx_live_storybook#2]
I just looked through the README and noticed that the story files are `.ex` files, but one also needs to supply a path for where those files are. I'm wondering if those files should rather be `.exs` files, so they're not compiled by default, but only used by the storybook. I feel like this is a similar setup to test files, which also are `.exs` files.

**Comment by cblavier** [comment]
Since all the storybook content is pre-compiled through macros, all stories would be executed at compile time to fetch their content.

We wouldn't benefit much from this change. Would we?

**Comment by LostKobrakai** [comment]
This is less about changing how those modules are used, if they're meant to be used, but more about that one probably doesn't really want those modules to continue to exist after compilation, in production, outside of the storybook, …. Just like test files are only compiled to run tests and only the ones which are actually executed.

**Comment by cblavier** [comment]
I think I got your point.
But do you think they would still belong to `/lib` folder?

**Comment by cblavier** [comment]
Thanks for your insight.  I'll try it with `exs` files and let you know how it goes!

(and you also deserve a special 🥇 for being the first issue opened here ;-)

**Comment by LostKobrakai** [comment]
I'm really interested in this, so happy to help. I've been a big fan of fractal, but it's not really a great fit for elixir and I've also tried to build similar projects before, but never got them anywhere usable.

**Comment by tmock12** [comment]
I'm curious, what if you _want_ them to exist in production compiled code? can you just hcange them back to `.ex` files  and maybe add the storybook directory to your `elixirc_paths/1` ?
