### ISSUE TITLE
Running phx_live_storybook against phx 1.7 assets issues 

### ISSUE THREAD

**Issue by michaelwa** [phenixdigital/phx_live_storybook#204]
i am running phx_live_storybook and i am not getting all of the assets, the page is rendering but there are 404 errors pointing to assets in locations that do not exist.

- phx v1.7.0-rc.0
- elixir 1.14.2
- node v10.19.0
- npm 6.14.4

i did find this issues article https://github.com/phenixdigital/phx_live_storybook/issues/84 but this is back in sept and likely was not referencing phx 1.7. 

i referenced the dependency as a git repository:
`{:phx_live_storybook,` git: "https://github.com/phenixdigital/phx_live_storybook.git"}

is there a different branch in the phx_live_storybook repository i should be using with phx 1.7?

i followed the steps from the article:
```
cd deps/phx_live_storybook
mix deps.get
npm ci --prefix assets
mix assets.build
```

however on the 'assets.build' step i get the following error:
❯ mix assets.build

> phx_live_storybook@1.0.0 build /home/michael_intandem/src/elixir_src/phx_1.7/teststorybook/deps/phx_live_storybook/assets
> npm-run-all build:*

> phx_live_storybook@1.0.0 build:css /home/michael_intandem/src/elixir_src/phx_1.7/teststorybook/deps/phx_live_storybook/assets
> tailwindcss --minify -i css/app.css -o ../priv/static/css/app.css

/home/michael_intandem/src/elixir_src/phx_1.7/teststorybook/deps/phx_live_storybook/assets/node_modules/tailwindcss/lib/cli.js:214
        throw err;
        ^
TypeError: Object.fromEntries is not a function
    at args (/home/michael_intandem/src/elixir_src/phx_1.7/teststorybook/deps/phx_live_storybook/assets/node_modules/tailwindcss/lib/cli.js:158:47)
    at Object.<anonymous> (/home/michael_intandem/src/elixir_src/phx_1.7/teststorybook/deps/phx_live_storybook/assets/node_modules/tailwindcss/lib/cli.js:216:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phx_live_storybook@1.0.0 build:css: `tailwindcss --minify -i css/app.css -o ../priv/static/css/app.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phx_live_storybook@1.0.0 build:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael_intandem/.npm/_logs/2022-12-22T18_16_05_310Z-debug.log
ERROR: "build:css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phx_live_storybook@1.0.0 build: `npm-run-all build:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phx_live_storybook@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael_intandem/.npm/_logs/2022-12-22T18_16_05_341Z-debug.log
** (exit) 1
    (mix 1.14.2) lib/mix/tasks/cmd.ex:74: Mix.Tasks.Cmd.run/1
    (mix 1.14.2) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.2) lib/mix/task.ex:479: Mix.Task.run_alias/6
    (mix 1.14.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2

**Comment by michaelwa** [comment]
found the issue ... i installed a really old version of node ... i just assumed 'apt' would return a decently recent version but alas it did not

**Comment by cblavier** [comment]
I'm glad you figured it out!
Btw, we now have a mix task to get the assets compiled (only required if you are using an unreleased version of storybook)

```
mix dev.storybook
```
