### ISSUE TITLE
CODECOV_TOKEN in the CI

### ISSUE THREAD

**Issue by dmarcoux** [phenixdigital/phx_live_storybook#222]
`CODECOV_TOKEN` should be treated as a secret and not be in plain text in a GitHub Actions workflow: https://github.com/phenixdigital/phx_live_storybook/blob/b9c6d88644448daba308e7b968a789b5e878ce58/.github/workflows/elixir.yml#L16

This allows anybody to push code coverage results to your CodeCov.

**Comment by cblavier** [comment]
Hey Dany, you're right!
This is one of these "temporary" things that last forever.
Will change the token and store it as as a secret right now

**Comment by cblavier** [comment]
Seems even easier, tokens are only required for private repositories: https://github.com/codecov/codecov-action
