### ISSUE TITLE
"Key :source not found" error from 0.14.3 to 0.14.5 version

### ISSUE THREAD

**Issue by dgigafox** [phenixdigital/phx_live_storybook#228]
We are now getting this error:

> key :source not found in: [engine: Phoenix.LiveView.HTMLEngine, caller: #Macro.Env<aliases: [{LiveViewEngine, Phoenix.LiveView.Engine}, {HTMLEngine, Phoenix.LiveView.HTMLEngine}, {RenderingContext, PhxLiveStorybook.Rendering.RenderingContext}, {RenderingVariation, PhxLiveStorybook.Rendering.RenderingVariation}, {TemplateHelpers, PhxLiveStorybook.TemplateHelpers}], context: nil, context_modules: [PhxLiveStorybook.Rendering.ComponentRenderer], file: "/Users/.../Projects/.../elixir/deps/phx_live_storybook/lib/phx_live_storybook/rendering/component_renderer.ex", function: {:render_component_heex, 3}, functions: [{Kernel, [!=: 2, !==: 2, *: 2, **: 2, +: 1, +: 2, ++: 2, -: 1, -: 2, --: 2, /: 2, <: 2, <=: 2, ==: 2, ===: 2, =~: 2, >: 2, >=: 2, abs: 1, apply: 2, apply: 3, binary_part: 3, binary_slice: 2, binary_slice: 3, bit_size: 1, byte_size: 1, ceil: 1, div: 2, elem: 2, exit: 1, floor: 1, function_exported?: 3, get_and_update_in: 3, get_in: 2, hd: 1, inspect: 1, inspect: 2, is_atom: 1, is_binary: 1, ...]}], lexical_tracker: nil, line: 137, macro_aliases: [], macros: [{Kernel, [!: 1, &&: 2, ..: 0, ..: 2, ..//: 3, <>: 2, @: 1, alias!: 1, and: 2, binding: 0, binding: 1, dbg: 0, dbg: 1, dbg: 2, def: 1, def: 2, defdelegate: 2, defexception: 1, defguard: 1, defguardp: 1, defimpl: 2, defimpl: 3, defmacro: 1, defmacro: 2, defmacrop: 1, defmacrop: 2, defmodule: 2, defoverridable: 1, defp: 1, defp: 2, defprotocol: 2, defstruct: 1, destructure: 2, get_and_update_in: 2, if: 2, ...]}], module: PhxLiveStorybook.Rendering.ComponentRenderer, requires: [Application, Kernel, Kernel.Typespec], ...>]

**Elixir version:**  1.14.3-otp-25
**Erlang version:** 25.2.1
**Node version:** v18.11.0
**phx_live_storybook versions:** We tried the 0.14.3 to 0.14.5 versions but had no luck

### Actions taken:
1. Remove _build and _deps folder
2. Re-running `mix deps.get` and `mix phx.server`

**Comment by zoedsoupe** [comment]
I'm having this same issue on version `0.4.4`

**Comment by cblavier** [comment]
This has been fixed in #221 (you have to pick the main branch though)
0.5.0 should be released really soon, one last ticket to finish
