### ISSUE TITLE
sandbox (story) items flexing to full width.

### ISSUE THREAD

**Issue by glennr** [phenixdigital/phx_live_storybook#26]
With the new flex-column layout of stories, I'm seeing elements expand to the width of the flexbox.

![image](https://user-images.githubusercontent.com/72130/185539724-073f8922-bcae-4df9-a6ba-56a996b90e18.png)

Expected:

![image](https://user-images.githubusercontent.com/72130/185539834-dd1f3dd9-85f1-4ae6-a16c-0dd67bad8d4c.png)

**Comment by cblavier** [comment]
Yes indeed, thanks for the PR
