### ISSUE TITLE
Event log in the component playground

### ISSUE THREAD

**Issue by cblavier** [phenixdigital/phx_live_storybook#33]
In the component Playground a new tab (next to the Attributes tab) should be available for all components.

This tab will print, in a `<pre>...</pre>` monospace font fashion:
- all messages (`handle_info` & `handle_event`) received by the component
- all messages (`handle_info` & `handle_event`)  received by the parent LiveView (`PlaygroundPreviewLive`) excepted the `{:new_attributes, pid, attrs}` which is for internal use
- all messages are prefixed with the recipient (component or Liveview)
- all messages are prefixed with their kind (info or event)

If messages are received when the Logs tab is not active, a badge will appear next to the tab name with the number of _unread logs_. The badge is cleared as soon as the tab is opened.

**Comment by dgigafox** [comment]
@cblavier are you working on this already? I wanted to give this one a try
I am thinking if we can use telemetry here to catch events
```elixir
@lv_events [
    [:phoenix, :live_view, :handle_event, :stop],
    [:phoenix, :live_component, :handle_event, :stop]
  ]

def start(_, _) do
...
:telemetry.attach_many(
      "phx-lv",
      @lv-events,
      &handle_event/4,
      nil
    )
...
end


  def handle_event(span, event, metadata, nil) when span in @lv_events do
    IO.inspect(event, label: "EVENT")
    IO.inspect(metadata, label: "META")

    :ok
  end
```

With this, we can get something like this:
```elixir
EVENT: %{duration: 11222, monotonic_time: -576460634209427886}
META: %{
  component: MyComponents.Compo,
  event: "toggle",
  params: %{"value" => ""},
  socket: #Phoenix.LiveView.Socket<
    assigns: %{
      __changed__: %{show: true},
      flash: %{},
      id: "compo-default-component",
      inner_block: [
        %{
          __slot__: :inner_block,
          inner_block: #Function<41.3316493/2 in :erl_eval.expr/6>
        }
      ],
      myself: %Phoenix.LiveComponent.CID{cid: 2},
      show: true
    },
    endpoint: MyWeb.Endpoint,
    id: "phx-Fw_P0A_tAWChAQaC",
    parent_pid: nil,
    root_pid: #PID<0.5624.0>,
    router: MyWeb.Router,
    transport_pid: #PID<0.5620.0>,
    view: PhxLiveStorybook.EntryLive,
    ...
  >,
  telemetry_span_context: #Reference<0.186454552.4109369348.61147>
}
```

**Comment by cblavier** [comment]
Feel free to ask for help if you want to understand how this is working under the hood, or if you don't know where you should put your code

**Comment by cblavier** [comment]
[Contributing guide](https://github.com/phenixdigital/phx_live_storybook/blob/main/CONTRIBUTING.md) is online

**Comment by dgigafox** [comment]
Hey @cblavier, thank you! I have started prototyping it already. Will share you the flow of message from preview to telemetry to LV that I have come up with later on and see if you agree with it.
