### ISSUE TITLE
How to add a modal to the storybook

### ISSUE THREAD

**Issue by dgigafox** [phenixdigital/phx_live_storybook#37]
First of all, thank you guys for your work on this!

I am having a hard time adding a modal to the storybook which is supposed to be something like this https://petal.build/components/modals. For a modal to show/hide, it needs a button, so in the sandbox it must also show a button and a modal that is hidden by default.

I already tried doing something like this:
```elixir
alias MyComponents.Modal

def function, do: &my_modal/1
def description, do: "Modals sit on top of an applications main window"

  def stories do
    [
      %StoryGroup{
        id: :sizes,
        description: "Different sizes of modal",
        stories: [
          %Story{
            id: :default_modal,
            attributes: %{title: "Testing"}
          }
        ]
      }
    ]
  end

  # For storybook purposes only
  def my_modal(assigns) do
    ~H"""
    <button
      class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
      type="button"
      data-modal-toggle="default-modal"
    >
      Toggle modal
    </button>

    <Modal.modal title="Testing123">Some testing</Modal.modal>
    """
  end
```

This should work, although the documentation now points to `my_modal/1` instead of just `Modal.modal/1`.

Are there any plans to pass a layout option to the sandbox so it will house the component instead of just a div/iframe option? Or in the current version, do you suggest any workaround to make this work?

**Comment by cblavier** [comment]
Hey, your use case sounds legit, so we have to make it work :)
Let me think about it and we'll figure something out!

**Comment by cblavier** [comment]
I didn't have much time to work on this, but I think we need a generic solution that would work for any component initialized in a hidden state, such as modal, slideovers, command palettes, or notification messages...

I was thinking of a new `trigger` option for components that you define on the component level, and that you can override per story. It would look like this: 

```elixir
defmodule Modal do
  use PhxLiveComponent, :component
  def function, &Modal.modal/1

  def trigger do
    {"button", label: "Show modal", toggle_assign: nil, show_code: true, html: [
       class: "p-2 bg-gray-100 text-gray-500", "phx-click": {JS.toggle(to: :story_component)}
    ]}
  end

  def stories do
    [
      %Story{
         name: "default",
         attributes: %{
           title: "My Modal",
           dismissable: true
         },
         slots: [
           "<:body>my modal content</:body>",
           "<:footer>my modal footer</:footer>"
         ],
         trigger: %{
           label: "Open the modal"
         }
      }
    ]
  end
end
```

This example would show a `Show modal` button for all stories that toggles it using JS commands.
What's your opinion on this solution?

**Comment by dgigafox** [comment]
@cblavier In my opinion, the trigger is too verbose and will be limited only to single elements. Also, there would be cases where we want to get information from `assigns` to the template, for example, we want to label the button with the size variant. I think what we can do is pass a function that can be used as a template, for example:

```elixir
defmodule Modal do
  use PhxLiveComponent, :component
  def function, do: &Modal.modal/1
  def template, do: &__MODULE__.modal_template/1

  def stories do
    [
      %Story{
         name: "default",
         attributes: %{
           title: "My Modal",
           dismissable: true
         },
         slots: ["<:footer>my modal footer</:footer>"],
         block: "my modal content"
      }
    ]
  end

  defp modal_template(assigns) do
    ~H"""
    <button phx-click={Modal.show_modal(@id)}>
      <%= @size %>
    </button>

    <.modal id={@id} title={@title} size={@size}>
      <%= render_slot(@inner_block) %>
      <:footer><%= render_slot(@footer) %></:footer>
    </.modal>
    """
  end
end
```

The idea is somehow similar to this https://storybook.js.org/docs/react/writing-stories/decorators#component-decorators and this https://storybook.js.org/docs/react/writing-stories/stories-for-multiple-components#creating-a-template-component

Currently, I tried the above where I put modal_template/1 to function/0. It works except that source code now points to the story itself and it returns an error on rendering stories when I added this:
`<:footer><%= render_slot(@footer) %></:footer>`

**Comment by cblavier** [comment]
I started prototyping the feature. Looking good so far!

```elixir
defmodule Storybook.Components.Modal do
  use PhxLiveStorybook.Entry, :component

  def function, do: &PhxLiveStorybookSampleWeb.Components.Modal.modal/1

  def template do
    """
    <div>
      <button phx-click={Modal.show_modal()}>Open modal</button>
      <.story/>
    </div>
    """
  end

  def stories do
    [
      %Story{
        id: :default_modal,
        slots: [
          "<:icon><i class='fa fa-check'></i></:icon>",
          "<:body>hello world</:body>"
        ]
      }
    ]
  end
end
```
![CleanShot 2022-08-25 at 17 50 47](https://user-images.githubusercontent.com/130783/186711992-91ef38d1-72f6-4aa1-be79-848199571ac3.gif)

**Comment by cblavier** [comment]
I extended this solution to also work with components that don't rely on JS components but need external assigns (like a modal that takes a `show={true}` or `show={false}` assign to manage their visibility state.

```elixir
defmodule Storybook.Components.Slideover do
  use PhxLiveStorybook.Entry, :component

  def function, do: &PhxLiveStorybookSampleWeb.Components.Slideover.slideover/1

  def template do
    """
    <div>
      <button phx-click="set-story-assign/show/true">Open slideover</button>
      <.story/>
    </div>
    """
  end

  def stories do
    [
      %Story{
        id: :default_slideover,
        attributes: %{
          close_event: "set-story-assign/default_slideover-assign/show/false"
        },
        slots: [
          "<:body>I'm on the right (default)</:body>"
        ]
      }
    ]
  end
end
```

**Comment by dgigafox** [comment]
Nice catch on this use case! Although I am just worried, what if we are trying to change an assign that has non-string or non-boolean type. I cannot think of any use case yet, though. Could overcomplicate, but I would suggest attaching a callback like:
```
fn "show_modal" -> [show: true] end
```
But I guess your current implementation suits well enough.

**Comment by cblavier** [comment]
I'm also a bit worried about datatypes and had to do some _special handling_  for booleans but I don't want to overcomplicate if this is not required (that's already quite complex for my taste)

I may change my mind as use cases emerge.

**Comment by cblavier** [comment]
I just figured out that types are actually defined in story attributes 🤦‍♂️

So if we are using: `phx-click="set-story-assign/story_id/temperature/42.2"` within a story declaring a matching attribute `"42.2"` is casted as `42.2`.

```elixir
%Attr{id: :temperature, type: :float}
```

If no attribute has been declared, it is assigned as a `string`. If there is a type mismatch, it raises.

**Comment by cblavier** [comment]
🎉

**Comment by dgigafox** [comment]
Thank you @cblavier! We definitely need this feature. Will wait for the next release.
