### ISSUE TITLE
Component and function callback for function component entry

### ISSUE THREAD

**Issue by LostKobrakai** [phenixdigital/phx_live_storybook#4]
It feels strange to duplicate the module for a function component on both the `component/0` and the `function/0` callback. I'm not sure I completely understand the system yet, but isn't the `function/0` return value enough to figure out the module it's on?

**Comment by cblavier** [comment]
I think you are right, I'll open a PR with that change.

**Comment by cblavier** [comment]
Thanks, it made even some code a bit more simple
