### ISSUE TITLE
Stories always passing an inner_block

### ISSUE THREAD

**Issue by glennr** [phenixdigital/phx_live_storybook#47]
Given this component

```
   def custom_link(%{link_type: "a"} = assigns) do
     ~H"""
     <%= Phoenix.HTML.Link.link([to: @to, class: @class] ++ @rest,
       do: if(@inner_block, do: render_slot(@inner_block), else: @label)
     ) %>
     """
   end
```

and this Story (without a `slot`)

```
          %Story{id: :default, attributes: %{label: "Link", to: "/"}},
          %Story{id: :slot, attributes: %{to: "/"}, slots: [~s|Default slot|]},
```

It wont render anything in the first Story in the storybook.

It appears that the Story is _always_ passing an `inner_block`, slot or not.

This is a workaround, but it's not ideal

```
-      do: if(@inner_block, do: render_slot(@inner_block), else: @label)
+      do: if(@label, do: @label, else: render_slot(@inner_block))
```

**Comment by cblavier** [comment]
Hey @glennr thanks for the report.
Just finishing my current ticket and I will investigate on this

**Comment by cblavier** [comment]
This is fixed 👌
Take care, your component code is broken, don't test inner_block with 

```elixir
<%= if @inner_block do %>
 @inner_block
<% end %>
```

but with

```elixir
<%= if assigns[:inner_block] do %>
 @inner_block
<% end %>
```

**Comment by glennr** [comment]
Thanks @cblavier!

> Take care, your component code is broken, don't test inner_block with

Indeed. However I omitted the line which enables the `@inner_block` shorthand:

```
  |> assign_new(:inner_block, fn -> nil end)
```

**Comment by glennr** [comment]
Sauce: https://github.com/petalframework/petal_components/blob/main/lib/petal_components/button.ex
