### ISSUE TITLE
nested components in Story.block ?

### ISSUE THREAD

**Issue by glennr** [phenixdigital/phx_live_storybook#48]
Hi! 

Any ideas how we should document this kind of `%Story{}`?

```
<.tabs>
  <.tab is_active to="/">Home</.tab>
  <.tab link_type="a" to="/" label="About" />
</.tabs>
```

I've tried `block`:

```
defmodule BrmblWeb.Storybook.Components.Navigation.Tabs do
  use PhxLiveStorybook.Entry, :component

  import BrmblWeb.UI.Navigation.Tabs

  def function, do: &BrmblWeb.UI.Navigation.Tabs.tabs/1

  def stories do
    [
      %Story{
        id: :tabs,
        attributes: %{},
        block: """
        <.tab is_active to="/" label="Tab1" />
        <.tab to="/hi" label="Tab2" />
        """
      }
    ]
  end
end
```

Which yields an opaque error: 

```
Compiling 2 files (.ex)

== Compilation error in file lib/brmbl_web/storybook.ex ==
** (CompileError) lib/brmbl_web/storybook.ex: an error occured while rendering story tabs
    (stdlib 3.17.2) lists.erl:1358: :lists.mapfoldl/3
    (stdlib 3.17.2) lists.erl:1359: :lists.mapfoldl/3
    (stdlib 3.17.2) lists.erl:1358: :lists.mapfoldl/3
    (phoenix_live_view 0.17.11) expanding macro: Phoenix.LiveView.Helpers.inner_block/2
```

Confirmed that plain old HTML inside a block works fine:

```
  def stories do
    [
      %Story{
        id: :tabs,
        attributes: %{},
        block: """
        <a>hi</a>
        <a>hi</a>
        """
      }
    ]
  end
```

Can we (do we need to) use sigil_H inside our story definitions?

**Comment by cblavier** [comment]
can you try using a fully qualified name in your block?

```elixir
%Story{
  id: :tabs,
  attributes: %{},
  block: """
  <BrmblWeb.UI.Navigation.Tabs.tab is_active to="/" label="Tab1" />
  <BrmblWeb.UI.Navigation.Tabs.tab to="/hi" label="Tab2" />
  """
}
```

**Comment by glennr** [comment]
That gets it to compile

The generated story remains verbose however:

```
<.tabs>
  <BrmblWeb.UI.Navigation.Tabs.tab is_active to="/" label="Tab1" />
<BrmblWeb.UI.Navigation.Tabs.tab to="/hi" label="Tab2" />
<./tabs>
```

(indentation appears broken, but Ive noticed that elsewhere)

**Comment by glennr** [comment]
Thanks for that - this un-blocks me for now!

**Comment by cblavier** [comment]
Ok I’ll improve it so that all functions in your component are automatically imported.

I’ll also check with indentation

**Comment by cblavier** [comment]
An entry example using new custom aliases / imports

```elixir
defmodule NestedComponent do
  use PhxLiveStorybook.Entry, :component
  def function, do: &NestedComponent.nested_component/1

  def aliases, do: [MyStorybook.Helpers.JSHelpers]
  def imports, do: [{NestedComponent, nested: 1}]

  def stories do
    [
      %Story{
        id: :default,
        block: """
        <.nested phx-click={JSHelpers.toggle()}>hello</.nested>
        <.nested phx-click={JSHelpers.toggle()}>world</.nested>
        """
      }
    ]
  end
end
```

**Comment by cblavier** [comment]
proper slots indentation 👌 

<img width="1141" alt="CleanShot 2022-09-02 at 12 09 41" src="https://user-images.githubusercontent.com/130783/188117156-95f15aea-b6c5-462b-a943-86931de126ca.png">

**Comment by glennr** [comment]
@cblavier just spotted this. Awesome stuff mate. 

You got a release candidate, or some other tag we can pull from?

**Comment by cblavier** [comment]
no release now, still a few tickets to ship.

In the meantime you can pull `main` branch. The issue is that, since it's not a proper hex release, you won't have the assets

in your `mix.exs` : 
```elixir
defp deps do 
  [{:phx_live_storybook, github: "phenixdigital/phx_live_storybook"}]
end
```

then from your shell

```bash
mix deps.get
cd deps/phx_live_storybook
mix deps.get
npm ci --prefix assets
mix assets.build
```

you should be ready to go, and take care of recent changes in `router.ex` (see `CHANGELOG.md`)

**Comment by glennr** [comment]
yeah I spotted those changes in the Changelog. I gave it a stab yesterday, but the assets were tripping me up. Thanks a bunch for the workaround!
