### ISSUE TITLE
Render Markdown in attribute docs

### ISSUE THREAD

**Issue by xxdavid** [phenixdigital/phx_live_storybook#516]
This was already mentioned in #180 but the Markdown rendering was not discussed further, so I am creating a separate issue just for that.

I think the `doc` field in `attr/3` is supposed to contain Markdown, see for example the docs for [`Phoenix.Component.live_title/1`](https://github.com/phoenixframework/phoenix_live_view/blob/d1901861e90fb60ab26326e213ec18f92b5d06da/lib/phoenix_component.ex#L2103-L2116). Therefore, I think the attribute docs in the Playground tab should also render Markdown.

This would probably need to style the attribute docs a bit, as in issue #514, so that, for example, bullet points are shown as bullet points.

**Comment by cblavier** [comment]
Hey, you're right, these topics were on hold until I shipped #425 
In the coming weeks, I will look at this issue, #180 and #514.

Would you consider that we pass the test if I manage to render the Phoenix core components doc properly?

**Comment by xxdavid** [comment]
Hi, that is awesome! Thank you so much! 🙂

It seems to me that `CoreComponents` ([source](https://github.com/phoenixframework/phoenix/blob/092605f4c3696c4bfe3a531b024030090c1ea23b/priv/templates/phx.gen.live/core_components.ex)) would a good test for the component docs (#514) but not much for the attribute docs as their attribute docs aren't really formatted. I would test the attribute docs on the components from `Phoenix.Component` ([source](https://github.com/phoenixframework/phoenix_live_view/blob/d1901861e90fb60ab26326e213ec18f92b5d06da/lib/phoenix_component.ex)) if it's possible, plus on some dummy attribute docs containing lists (`<ul>`/`<ol>`). I can surely help with testing if you want.

**Comment by cblavier** [comment]
I'm about to ship this (along with #514)

**Attribute documentation:**

![CleanShot 2024-12-16 at 16 59 43](https://github.com/user-attachments/assets/8376701a-ec44-4616-ab4c-87359e346498)

**Nested slot attributes documentation:**

![CleanShot 2024-12-16 at 16 58 47](https://github.com/user-attachments/assets/d06407bc-62fe-4410-90e1-a8005eb91603)

**Comment by xxdavid** [comment]
Wow, looks great! And the addition of slot attributes is also cool! Thanks for your hard work! 🙂
