### ISSUE TITLE
Wrong closing tag

### ISSUE THREAD

**Issue by jeffdelara** [phenixdigital/phx_live_storybook#53]
Its generating the wrong closing tag:

![Screen Shot 2022-09-02 at 1 52 22 PM](https://user-images.githubusercontent.com/89393265/188068017-6b8c2a37-63ce-42b9-9746-55a54f57781d.png)

Should be `</.footer>`

**Comment by cblavier** [comment]
Thanks for reporting!
Always doing the same typo 🤦‍♂️

**Comment by cblavier** [comment]
Code indentation also seems completely broken, I will fix this in another PR

**Comment by cblavier** [comment]
proper slots indentation 👌 

<img width="1141" alt="CleanShot 2022-09-02 at 12 09 41" src="https://user-images.githubusercontent.com/130783/188117156-95f15aea-b6c5-462b-a943-86931de126ca.png">
