### ISSUE TITLE
How do we pass `let` variable to a block in a story

### ISSUE THREAD

**Issue by dgigafox** [phenixdigital/phx_live_storybook#59]
If I have a component that can pass an argument to its inner block that can be accessed via a `let` property, how do we do it in a story?

For example, my component looks like this:
```elixir
~H"""
<.my_component let={m} ...>
  <div class={m.classes}>...</div>
</.my_component>
"""
```

I tried something like:
```elixir
def stories do
    [
      %Story{
        id: :default,
        attributes: %{
          id: "default",
          let: m
        },
        block: """
        <div class={m.classes}>...</div>
        """
      }
    ]
  end
```

But of course, this will produce an `undefined function m/0`.

**Comment by cblavier** [comment]
This is merged, with documentation [here](https://github.com/phenixdigital/phx_live_storybook/blob/main/guides/components.md#block-slots--let)

Let me know of this works for you!
