### ISSUE TITLE
Storybook has to be refreshed to show Date Picker

### ISSUE THREAD

**Issue by hendri-tobing** [phenixdigital/phx_live_storybook#73]
I want to say thank you for your great work on phx_live_storybook!

We have one issue when using Date Picker in the Storybook. The date picker is not shown, unless storybook page is refreshed once.

We are using https://flowbite.com/docs/plugins/datepicker which is basically a Tailwind CSS date picker.

Is it because of the components are rendered during compile time and refreshing the page re-renders the component and activating the hook? 

Thank you.

**Comment by cblavier** [comment]
Hey Hendri 👋

I assume you are using 0.3.0
Lots of things have changed since, and 0.4.0 should be ready in a couple of weeks.

Can you try using the main branch and tell me if you are still experiencing the issue?

Instructions to use main branch: https://github.com/phenixdigital/phx_live_storybook/issues/48#issuecomment-1237880396

**Comment by hendri-tobing** [comment]
Thank you for the prompt response.

I have tried the latest main branch, and updated the router.ex.

It seems the datepicker works properly in the Stories tab, without refreshing the page 👍🏽

However, in the Playground tab it seems still need a refresh to make it works. 

Thanks.

**Comment by cblavier** [comment]
I have no clue, maybe move your JS init code (in your Hook) from the `mount()` callback to the `update()` callback?
You can also send me component, story, and hook files if you want me to investigate a bit further

**Comment by cblavier** [comment]
Hey, is this still an issue?

**Comment by dgigafox** [comment]
Hi @cblavier,
@hendri-tobing is my colleague and yes this is still an issue. Not just hooks though, but any imported JS from the app.
For example in our app.js, we have:
```
import "flowbite";
import "flowbite/dist/datepicker";
```
This has scripts related to interactive components such as accordion, dropdown, datepicker, etc... When we open those stories we need to refresh again just to make the JS work. This is in v0.3.0

We tried the latest main branch, just 2 days ago, but now imported JS totally does not work. Not sure now which breaks it 🤔

**Comment by cblavier** [comment]
Sorry for the delay but I put this issue on hold until some really big refactoring tickets are finished.
0.4.0 is now around the corner, but a lot of breaking changes have been recently introduced, which really won't help us at investigating your issue.
I'll ping you here pre 0.4.0 release to figure out what's happening.

**Comment by cblavier** [comment]
Most of the _pre 0.4.0_ refactoring has been done now.
You should update to the latest `main` version (which involves a lot of changes, including switching to LiveView 0.18.0) and try to reproduce the issue.

**Comment by cblavier** [comment]
👋 Did you have a change to test your app against storybook 0.4.1?

**Comment by cblavier** [comment]
A lot of moving parts these days! 
Just went through the migration myself ;-)

**Comment by dgigafox** [comment]
@cblavier thanks for waiting for our response. I think I found the answer now. I tried to look inside flowbite's source code and it is just initializing accordions on document's ready state like this:

```js
if (document.readyState !== 'loading') {
	// DOMContentLoaded event were already fired. Perform explicit initialization now
	initAccordion()
} else {
	// DOMContentLoaded event not yet fired, attach initialization process to it
	document.addEventListener('DOMContentLoaded', initAccordion)
}
```

The page needs to be refreshed for it to call this again. We need to find a way to hook this code to accordion's mounted lifecycle via phx-hook. The same case with datepicker.

cc: @hendri-tobing

**Comment by cblavier** [comment]
Yes you should call `initAccordion` in your hook mount callback
It doesn't seem to be related to the storybook, may I close the ticket?

**Comment by dgigafox** [comment]
Yup probably not related to storybook. Sure, please close
