### ISSUE TITLE
Lazy loading of stories

### ISSUE THREAD

**Issue by cblavier** [phenixdigital/phx_live_storybook#78]
Component & pages `.exs` files are compiled as a whole at compilation time (triggered by the compilation of the storybook backend module defined in the user application).

As the codebase grows, this could induce increased compilation times.

Components & pages `exs` files should instead: 
- be **eagerly compiled** in `prod` env
- be **lazily compiled** at page load in any other environment

**Comment by josevalim** [comment]
Regarding prod being eager, that's likely important but we need to be careful because most people likely won't run storybooks in prod?

**Comment by cblavier** [comment]
I do run the storybook in prod. I think it is a very valuable tool to share a design system with UI/UX designers

But we can make it an opt-in setting (disabled in prod by default)
